# Generated by Django 5.1.15 on 2026-08-15 22:01

import apps.accounts.managers
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('nickname', models.CharField(blank=True, help_text='Apelido, opcional.', max_length=50)),
                ('rgm', models.CharField(blank=True, help_text='Obrigatório e exclusivo para estudantes (CSStudent).', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O RGM deve conter apenas números.', regex='^\\d+$')])),
                ('role', models.CharField(choices=[('cs_admin', 'CSAdmin'), ('cs_coordinator', 'CSCoordinator'), ('cs_student', 'CSStudent')], default='cs_student', max_length=20)),
                ('must_change_password', models.BooleanField(default=False, help_text='Se True, o usuário precisa trocar a senha antes de usar o resto da API.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('coordinated_courses', models.ManyToManyField(blank=True, help_text='Cursos coordenados por este usuário. Só se aplica a CSCoordinator.', related_name='coordinators', to='accounts.course')),
                ('course', models.ForeignKey(blank=True, help_text='Curso do estudante. Não se aplica a CSAdmin/CSCoordinator.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.course')),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
