# Generated by Django 5.1.15 on 2026-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil, opcional.', null=True, upload_to='avatars/'),
        ),
    ]
