# Generated by Django 5.1.15 on 2026-08-16 15:53

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        # No-op onde a extensão já existe (bootstrap_db); necessário no banco de testes.
        VectorExtension(),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
