# Generated by Django 5.1.15 on 2026-08-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='heading',
            field=models.CharField(blank=True, help_text="Caminho de seções do documento a que o chunk pertence (ex.: '5. Modelo ER > 5.1 Entidades'), quando o formato permite extrair isso.", max_length=500),
        ),
    ]
