# Generated by Django 5.1.15 on 2026-10-02 05:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_gin'),
        ),
    ]
