# Generated by Django 5.1.15 on 2026-10-02 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
        ('documents', '0006_popula_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('semestre', models.PositiveSmallIntegerField(blank=True, help_text='Semestre curricular no curso.', null=True)),
                ('carga_horaria', models.PositiveSmallIntegerField(blank=True, help_text='C/H semestral, em horas.', null=True)),
                ('periodo_letivo', models.CharField(blank=True, help_text='Período do plano, ex.: 2025/1.', max_length=10)),
                ('index_inicio', models.PositiveIntegerField(blank=True, help_text='Índice do primeiro chunk do plano dentro do documento.', null=True)),
                ('course', models.ForeignKey(blank=True, help_text='Curso do plano (resolvido pelos cursos do documento); vazio se ambíguo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='accounts.course')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='documents.document')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['semestre', 'nome'],
            },
        ),
    ]
