# Generated by Django 5.1.15 on 2026-09-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Útil'), (-1, 'Não útil')], help_text='Avaliação do usuário sobre a resposta (só em mensagens do assistente).', null=True),
        ),
    ]
