# Generated by Django 5.1.15 on 2026-10-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback_comment',
            field=models.TextField(blank=True, help_text='Comentário opcional do 👎 (até 500 caracteres).'),
        ),
        migrations.AddField(
            model_name='message',
            name='feedback_reason',
            field=models.CharField(blank=True, choices=[('incorreta', 'Incorreta'), ('incompleta', 'Incompleta'), ('nao_entendeu', 'Não entendeu'), ('fora_do_curso', 'Fora do curso'), ('outro', 'Outro')], help_text='Motivo do 👎 (só quando feedback = -1). Alimenta o golden set e os relatórios.', max_length=20),
        ),
        migrations.CreateModel(
            name='MessageTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_version', models.CharField(blank=True, max_length=20)),
                ('route', models.CharField(blank=True, max_length=40)),
                ('intent', models.CharField(blank=True, max_length=40)),
                ('route_source', models.CharField(blank=True, choices=[('l0', 'Regras (L0)'), ('l1', 'Modelo (L1)'), ('fallback', 'Fallback'), ('legacy', 'Pipeline legado')], max_length=20)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ttft_ms', models.PositiveIntegerField(blank=True, help_text='Tempo até o primeiro token.', null=True)),
                ('steps', models.JSONField(blank=True, default=list, help_text='Lista de {type, name, ms, ...}.')),
                ('chunk_ids', models.JSONField(blank=True, default=list)),
                ('distances', models.JSONField(blank=True, default=list)),
                ('guard_flags', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('models', models.JSONField(blank=True, default=dict, help_text='Modelo usado por papel: {papel: modelo}.')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trace', to='conversations.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
