# Generated by Django 5.1.15 on 2026-10-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_observabilidade_e_feedback_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Estado do roteador na conversa: `course` (curso resolvido: cc/ads, preenchido uma vez), `hint_level` (nível atual da escada de dicas, 1 a 3) e `last_intent`.'),
        ),
    ]
